export const SELECT_PHOTO = "SELECT_PHOTO";

export const FETCH_PHOTO_PENDING = "FETCH_PHOTO_PENDING";
export const FETCH_PHOTO_SUCCESS = "FETCH_PHOTO_SUCCESS";
export const FETCH_PHOTO_FAILURE = "FETCH_PHOTO_FAILURE";

export const FETCH_FAVPHOTO_PENDING = "FETCH_FAVPHOTO_PENDING";
export const FETCH_FAVPHOTO_SUCCESS = "FETCH_FAVPHOTO_SUCCESS";
export const FETCH_FAVPHOTO_FAILURE = "FETCH_FAVPHOTO_FAILURE";
